-- Find total amount paid by each customer
select customerNumber, sum(amount) as total_amount
from classicmodels.payments
group by customerNumber;

-- Find total number of payments made by each customer
select customerNumber, count(amount) as TotalNumPay
from classicmodels.payments
group by customerNumber;

-- Find the average payment amount for each customer
select customerNumber, avg(amount) as AvgPayment
from classicmodels.payments
group by customerNumber;

-- Find total revenue generated by each customer
select o.customerNumber, sum(od.quantityOrdered * priceEach) as total_revenue
from classicmodels.orderdetails od 
left join classicmodels.orders o
on od.orderNumber = o.orderNumber
group by o.customerNumber;

-- customers who have made more than 3 payments
select customerNumber, count(*) as total_payments
from classicmodels.payments
group by customerNumber
having count(*) > 3;

-- Find total number of orders placed by each customer
select customerNumber, count(*) as TotalNoOrders
from classicmodels.orders
group by customerNumber;

-- Find total revenue generated by each product
select p.productName, sum(quantityOrdered * priceEach) as 
TotalRevPerProduct from classicmodels.orderdetails od
left join classicmodels.products p 
on od.productCode = p.productCode
group by p.productName;

-- total revenue generated by each product line
select p.productLine, sum(quantityOrdered * priceEach) as 
TotalRevPerProduct from classicmodels.orderdetails od
left join classicmodels.products p 
on od.productCode = p.productCode
group by p.productLine;

-- total number of customers in each country
select country, count(*) as TotalNoCust 
from classicmodels.customers
group by country;

-- total revenue generated by each country
select c.country, sum(od.quantityOrdered * od.priceEach) as total_revenue
from classicmodels.orderdetails od
join classicmodels.orders o
on od.orderNumber = o.orderNumber
join classicmodels.customers c
on o.customerNumber = c.customerNumber
group by c.country;

-- average order value for each customer
select o.customerNumber, sum(od.quantityOrdered * od.priceEach)/count(distinct o.orderNumber)
as AvgOrderVal from classicmodels.orderdetails od
left join classicmodels.orders o 
on od.orderNumber = o.orderNumber
group by o.customerNumber;

-- employees and how many customers they manage
select e.employeeNumber, c.customerNumber, c.customerName,
count(*) as NoOfCust
from classicmodels.employees e 
inner join classicmodels.customers c 
on e.employeeNumber = c.salesRepEmployeeNumber
group by c.customerNumber, c.customerName;

-- offices and how many employees work in each office
select e.officeCode, e.reportsTo, count(*) as NoOfEmpl
from classicmodels.employees e 
inner join classicmodels.offices o 
on e.officeCode = o.officeCode
group by e.officeCode,e.reportsTo;

-- Show total amount spent by each customer
 select customerNumber, sum(amount) as Totalspent 
 from classicmodels.payments
 group by customerNumber;
 
 -- the countries where the count of customers >=5
select country, count(customerNumber) from classicmodels.customers 
group by country having count(customerNumber) >=5;