-- customer name, order number, and order date
select c.customerName, c.customerNumber, o.orderNumber, o.orderDate
from classicmodels.customers c 
left join classicmodels.orders o 
on c.customerNumber = o.customerNumber; 

-- customer name and their total payment amount
select c.customerNumber, c.customerName,
sum(p.amount) as totalPayment
from classicmodels.customers c 
left join classicmodels.payments p 
on c.customerNumber = p.customerNumber
group by c.customerNumber, c.customerName;

-- orders along with product names and quantities ordered
select p.productName, o.quantityOrdered
from classicmodels.products p 
left join classicmodels.orderdetails o 
on p.productCode = o.productCode
order by quantityOrdered desc;

--  employees and the offices they work in
select e.employeeNumber, o.officeCode, e.jobTitle
from classicmodels.employees e
left join classicmodels.offices o 
on e.officeCode = o.officeCode;

--  customers who have no orders
select c.customerNumber, c.customerName
from classicmodels.customers c 
left join classicmodels.orders o 
on c.customerNumber = o.customerNumber
where o.customerNumber is NULL;

-- total sales amount per customer
select c.customerNumber,
sum(p.amount) as TotalSales
from classicmodels.customers c
left join  classicmodels.payments p
on c.customerNumber = p.customerNumber
group by customerNumber;

--  all products that have never been ordered
select o.orderNumber
from classicmodels.orders o 
left join classicmodels.orderdetails od
on o.orderNumber = od.orderNumber
where od.orderNumber;

-- order details including product name and price
select p.productName, o.priceEach
from classicmodels.products p 
left join classicmodels.orderdetails o 
on p.productCode = o.productCode;

-- sales representative name and their customers
select e.firstName as salesRepFirstName, e.lastName as salesRepLastName, c.customerName
from classicmodels.employees e
join classicmodels.customers c 
on e.employeeNumber = c.salesRepEmployeeNumber
order by e.lastName, c.customerName;

-- which office has the highest number of employees
select officeCode,
count(employeeNumber) as NumOfEmpl
from classicmodels.employees
group by officeCode
order by NumOfEmpl desc
limit 1;

-- Show the customer name and order number for customers who have placed at least one order
select c.customerName, o.orderNumber 
from classicmodels.customers c 
inner join classicmodels.orders o 
on c.customerNumber = o.customerNumber;

-- Display the order number, product name, quantity ordered, and price each for all ordered products
select od.orderNumber, p.productName, od.quantityOrdered, od.priceEach
from classicmodels.orderdetails od
inner join classicmodels.products p
on od.productCode = p.productCode;

-- List the customer name, payment date, and amount for customers who have made payments
select c.customerName, p.paymentDate, p.amount
from classicmodels.customers c
inner join classicmodels.payments p
on c.customerNumber = p.customerNumber;

-- total quantity sold and total revenue for each product
select p.productName, sum(o.quantityOrdered) as TotalQuantity,
sum(o.quantityOrdered * o.priceEach) as TotalRevenue from classicmodels.products p
inner join classicmodels.orderdetails o 
on p.productCode = o.productCode
group by p.productName;

-- Show the employee name and the customers they handle
select concat(e.firstName,' ',e.lastName) as EmployeeName, 
c.customerName,c.customerNumber
from classicmodels.employees e
inner join classicmodels.customers c 
on e.employeeNumber = c.salesRepEmployeeNumber;

-- Show all orders and the customer name, even if some orders do not have a matching customer
select c.customerName, o.orderNumber
from classicmodels.customers c
right join classicmodels.orders o
on c.customerNumber = o.customerNumber;

-- Display all payments along with customer names, including payments that are not linked to any customer
select c.customerNumber, c.customerName, p.amount
from classicmodels.customers c
right join classicmodels.payments p
on p.customerNumber = c.customerNumber;

-- List all order details and their product names, even if some order records do not have a matching product
select o.orderNumber, o.productCode, o.quantityOrdered,
o.priceEach, o.orderLineNumber, p.productName
from classicmodels.products p
right join classicmodels.orderdetails o
on p.productCode = o.productCode;

-- Find orders that do not have a corresponding customer 
select c.customerName, c.customerNumber, o.orderNumber
from classicmodels.customers c
right join classicmodels.orders o 
on c.customerNumber = o.customerNumber
where c.customerNumber is null;

-- find the total revenue generated by each product 
select p.productName, od.productCode,
sum(od.quantityOrdered * priceEach) as total_revenue
from classicmodels.orderdetails od
join classicmodels.products p
on od.productCode = p.productCode
group by od.productCode,p.productName
order by total_revenue desc;

-- -- Find total number of payments made by each customer
select customerNumber, count(amount) as TotalNumPay
from classicmodels.payments
group by customerNumber;

-- unbounded preceding and following
select customerNumber, paymentDate, sum(amount)
over(partition by customerNumber order by paymentDate rows between
unbounded preceding and unbounded following) as running_amt
from classicmodels.payments;










